server:
  port: 9080
  shutdown: graceful
  tomcat:
    max-swallow-size: 1MB
  servlet:
    context-path: /

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 60000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  server:
    port: 11211
  endpoints:
    web:
      exposure:
        include: '*'